- name: Fetching aws-cli
  copy:
    src: install-aws-cli.sh
    dest: $HOME/install-aws-cli.sh

- name: Changing permission of aws script to executable
  become: true
  become_user: ubuntu
  file:
    path: $HOME/install-aws-cli.sh
    mode: '777'

- name: Copying jenkins installation script
  copy:
    src: install-jenkins.sh
    dest: $HOME/install-jenkins.sh

- name: Change permission of jenkins script to executable
  become: true
  become_user: ubuntu
  file:
    path: $HOME/install-jenkins.sh
    mode: '777'

- name: Copying kubectl script
  copy:
    src: install-kubectl.sh
    dest: $HOME/install-kubectl.sh

- name: Change permission of kubectl script to executable
  become: true
  become_user: ubuntu
  file:
    path: $HOME/install-kubectl.sh
    mode: '777'

- name: Copying docker script
  copy:
    src: install-docker.sh
    dest: $HOME/install-docker.sh

- name: Change permission of docker script to executable
  become: true
  become_user: ubuntu
  file:
    path: $HOME/install-docker.sh
    mode: '777'